### ISSUE TITLE
Could you please add a LICENSE file to clarify what license this repository is under?

### ISSUE THREAD

**Issue by theangrydev** [chrisfcarroll/OCPKatas#2]
I'd like to understand what license this repository is under please

**Comment by chrisfcarroll** [comment]
Hola! Would GPL3 work for you, if I add that now?

**Comment by theangrydev** [comment]
Entirely up to you, whatever you are comfortable with 😄 I personally would prefer something permissive like MIT, but if you would like it to stay copy-left then I completely understand. Thanks!

**Comment by chrisfcarroll** [comment]
Somehow I like copyleft :-) I've added GPL3

**Comment by chrisfcarroll** [comment]
done!

**Comment by theangrydev** [comment]
Thank you

**Comment by codecop** [comment]
I think this issue could be closed. Thank you
